### ISSUE TITLE
Upgrade nodejs

### ISSUE THREAD

**Issue by rutra8002** [JetBrains/writerside-github-action#10]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, Jetbrains/writerside-github-action@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by lananovikova10** [comment]
Hello, Rutra! Thanks for bringing this to our attention. We're pleased to inform you that we've made an upgrade from Node.js version 16 to version 20. You don't need to take any action on your part, and this update should help alleviate any notifications you may have received from GitHub regarding outdated Node versions.

**Comment by lananovikova10** [comment]
Hello, Rutra! Thanks for bringing this to our attention. We're pleased to inform you that we've made an upgrade from Node.js version 16 to version 20. You don't need to take any action on your part, and this update should help alleviate any notifications you may have received from GitHub regarding outdated Node versions.

**Comment by teaGod-s** [comment]
Node.js 20 actions are deprecated. The following actions are running on Node.js 20 and may not work as expected: JetBrains/writerside-github-action@v4. Actions will be forced to run with Node.js 24 by default starting June 16th, 2026. Node.js 20 will be removed from the runner on September 16th, 2026. Please check if updated versions of these actions are available that support Node.js 24. To opt into Node.js 24 now, set the FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true environment variable on the runner or in your workflow file. Once Node.js 24 becomes the default, you can temporarily opt out by setting ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true. For more information see: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
