### ISSUE TITLE
plantuml style Issue with Korean

### ISSUE THREAD

**Issue by Lee-Minjea** [JetBrains/writerside-github-action#12]
Hi.

I got a style issue with rendering plantuml.

When plantuml diagram renders in IDE preview.
It looks great 
![image](https://github.com/JetBrains/writerside-github-action/assets/8085040/bfd31037-287a-4a17-a2a3-844ed1b4451b)

But when it renders into html with this action.
Korean style crashes.

<img width="726" alt="image" src="https://github.com/JetBrains/writerside-github-action/assets/8085040/11a14731-4073-47ec-a878-bc0641c61bd7">

I guess it's related to teexLength Attribute of test elements

Is there a option for styling plantutml ?
or making it look as same as preview ?

**Comment by lananovikova10** [comment]
Hello! Apologies for the delayed response. We've identified the issue you mentioned and have created a YouTrack ticket for it. You can track the progress of the resolution through this link: [YouTrack Issue - WRS-5151](https://youtrack.jetbrains.com/issue/WRS-5151/Issue-with-rendering-plantUML-with-Korean-symbols). Thank you for bringing this to our attention!
