### ISSUE TITLE
Support for PDF export

### ISSUE THREAD

**Issue by bwalter089** [JetBrains/writerside-github-action#14]
Currently, only HTML export is supported. Having support for PDF export would be great, too.

**Comment by lananovikova10** [comment]
Yes, we don't currently produce PDFs as part of the Docker image. We have an ongoing feature request regarding this: https://youtrack.jetbrains.com/issue/WRS-4528/Make-the-builder-to-produce-a-PDF-artifact. Feel free to upvote it so that we can prioritize.
