### ISSUE TITLE
GHA Error: cannot parse CLI arguments unrecognized option: -time

### ISSUE THREAD

**Issue by jjjermiah** [JetBrains/writerside-github-action#15]
I just got this error on a documentation build. I just started using writerside so maybe I might be missing some details but the build was working a few days ago. 

[Error in my repo](https://github.com/bhklab/ORCESTRA-api/actions/runs/8835894309/job/24261636543)

Error Screenshot:
![image](https://github.com/JetBrains/writerside-github-action/assets/44614774/75fdac1f-779f-4ee4-833d-6c157a54a455)

![image](https://github.com/JetBrains/writerside-github-action/assets/44614774/a934ecff-4422-4339-bd04-8cf0395723d3)

I believe this originates from this commit : https://github.com/JetBrains/writerside-github-action/commit/7b8763947e322131330ff6e41cd94af1150ac3d2

[worked 2 days ago](https://github.com/bhklab/ORCESTRA-api/actions/workflows/build_pages.yaml)

It might be helpful to release new github actions versions with appended versioning, (i.e v4.1)
since v4 worked before this commit.

**Comment by lananovikova10** [comment]
Hello! We apologize for the inconvenience. It seems we made a wrong decision by not bumping the version as intended. We will promptly roll back the changes and ensure that the release is properly labeled as v5. Thank you for your understanding. The announcement in the comminuty Slack will follow.
