### ISSUE TITLE
Documentation still makes reference to unnecessary artifact parameter

### ISSUE THREAD

**Issue by KDean-Dolphin** [JetBrains/writerside-github-action#22]
ARTIFACT has been removed from the [env declaration in README.md](https://github.com/JetBrains/writerside-github-action/blob/15d6f5983d681470988c442b166d5de54cae7b05/README.md?plain=1#L47), but it is still referenced in multiple places later in the file.

https://github.com/JetBrains/writerside-github-action/blob/15d6f5983d681470988c442b166d5de54cae7b05/README.md?plain=1#L87

https://github.com/JetBrains/writerside-github-action/blob/15d6f5983d681470988c442b166d5de54cae7b05/README.md?plain=1#L95

https://github.com/JetBrains/writerside-github-action/blob/15d6f5983d681470988c442b166d5de54cae7b05/README.md?plain=1#L156

https://github.com/JetBrains/writerside-github-action/blob/15d6f5983d681470988c442b166d5de54cae7b05/README.md?plain=1#L164

**Comment by siarb** [comment]
Thank you, fixed!
I also will fix it in the Writerside documentation examples.
