### ISSUE TITLE
Math Equation Rendering

### ISSUE THREAD

**Issue by EyeEyeloving** [JetBrains/writerside-github-action#6]
I newly downloaded writerside, but it cannot render mathematical formulas, including markdown methods and latex methods. Is there any plug-in missing? Or is it not supported at all?

**Comment by borlander** [comment]
I am looking at the problem right now, you may vote and follow the ticket https://youtrack.jetbrains.com/issue/WRS-2434.

As a workaround, if your documentation does NOT have API docs, I may be able to build an ad hoc docker image that is able to render the mermaid and math (but will fail on API docs). Will it be of any help?

**Comment by borlander** [comment]
Could you please try with an experimental docker image `registry.jetbrains.team/p/writerside/builder/writerside-builder:2.1.1593-p4431` 

I expect it to be the complete fix to WRS-2434, so it should be able to render everything. 
If this still does not work, please attach the logs from the launch, here or as an attachment to https://youtrack.jetbrains.com/issue/WRS-2434 (note that it also supports private attachments, if needed)
