### ISSUE TITLE
Builds with this action fail with PluginManager errors

### ISSUE THREAD

**Issue by infotexture** [JetBrains/writerside-github-action#8]
I set up a test repo to build docs using this action per https://www.jetbrains.com/help/writerside/deploy-docs-to-github-pages.html, but builds fail with errors that seem to be related to problems in the Docker container.

```
2023-12-30 23:27:37,648 [    283] SEVERE - #c.i.i.p.PluginManager - Problems found loading plugins:
  The Android Design Tools (id=com.android.tools.design, path=/opt/builder/plugins/design-tools) plugin Plugin 
'Android Design Tools' requires plugin 'Android' to be enabled
```

For details, see: https://github.com/infotexture/ot-docs-writerside/actions/runs/7366938372/job/20049651011#step:3:72

From what I see in the log, the failure doesn't seem to be related to the docs content I'm trying to publish.

Is there anything I can change to make this work, or does something need to be fixed in the container/image?

**Comment by EmmanueleVilla** [comment]
Same problem here, it seems the docker image is missing those plugins

**Comment by infotexture** [comment]
@makingthematrix Any idea who might be able to help nudge this along? 🙏

**Comment by EmmanueleVilla** [comment]
@borlander any news about this? do we need to open a ticket elsewhere?

**Comment by CoCreate-SMWLucasO** [comment]
Bump. I would like to use this for our documentation. However, automated deployment is very important to us.

**Comment by infotexture** [comment]
@CoCreate-SMWLucasO Thanks for the suggestion, glad you found a solution that works on your side.

I'm still getting errors that suggest issues with the Docker image:

```
java.lang.Throwable: Cannot find module "Writerside" in solution "workspace".
```

Since there's been no response from JetBrains 3 months later, I'm not particularly confident they intend to support this. 😥

**Comment by CoCreate-SMWLucasO** [comment]
> @CoCreate-SMWLucasO Thanks for the suggestion, glad you found a solution that works on your side.
> 
> I'm still getting errors that suggest issues with the Docker image:
> 
> ```
> java.lang.Throwable: Cannot find module "Writerside" in solution "workspace".
> ```
> 
> Since there's been no response from JetBrains 3 months later, I'm not particularly confident they intend to support this. 😥

Make sure you've configured the INSTANCE and ARTIFACT correctly. I validated my own configuration by looking over that other person's files in the Writerside folder vs what I myself have, where you might notice some interesting differences you could try.

**Comment by SMWLucasO** [comment]
Heya @infotexture 

I've made an example repository which you can reference here: https://github.com/SMWLucasO/deployable-writerside-documentation

I've highlighted some issues you have in your current repo in the README.md as well.

Hope this helps

**Comment by infotexture** [comment]
🙏 Thanks Lucas, that's very kind of you.

> There should be a 'Writerside' folder

I'm afraid you may be right about that. 😥 

I'm not a fan of tools dictating information architecture, and had indeed refactored my sample repo to use a more generic structure. The modified paths are registered in the configuration file [writerside.cfg#L5](https://github.com/infotexture/ot-docs-writerside/blob/master/writerside.cfg#L5), which worked locally.

But it's quite possible that the Docker image is hard-coded to expect and generate the default paths, rather than respecting the contents of the configuration file.

**Comment by lananovikova10** [comment]
> 🙏 Thanks Lucas, that's very kind of you.
> 
> > There should be a 'Writerside' folder
> 
> I'm afraid you may be right about that. 😥
> 
> I'm not a fan of tools dictating information architecture, and had indeed refactored my sample repo to use a more generic structure. The modified paths are registered in the configuration file [writerside.cfg#L5](https://github.com/infotexture/ot-docs-writerside/blob/master/writerside.cfg#L5), which worked locally.
> 
> But it's quite possible that the Docker image is hard-coded to expect and generate the default paths, rather than respecting the contents of the configuration file.

Hello, @infotexture! Apologies for the delayed response, and thank you for your patience.

Regarding the initial message about the plugins, it can be disregarded as they are not causing the build to fail. Our generator relies on the JetBrains platform PSI and various IntelliJ plugins, making it currently dependent on running within the IntelliJ platform (IDEA Community Edition is sufficient). The message you're seeing is from IDEA attempting to run the plugin at startup, which we've disabled to prevent freezing issues by removing both Maven and Gradle plugins from our builder.

As for the second issue, it appears to indicate an incorrect help module name specification. This refers to the folder containing the documentation contents. While the default name is "Writerside" when you create a new project, it's not mandatory. You can rename the folder or specify a different one by updating the writerside.cfg file in the <module> element. If you need further assistance or clarification, feel free to reach out.

Read more about it here: https://www.jetbrains.com/help/writerside/projects.html#help_module 

I have set up the notifications properly, so now you can write to us here.
